name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv & restore cache
        uses: astral-sh/setup-uv@v7.3.1
        with:
          enable-cache: true
          cache-dependency-glob: |
            backend/uv.lock
            backend/pyproject.toml

      - name: Sync dependencies
        working-directory: backend
        run: uv sync --frozen

      - name: Run tests
        working-directory: backend
        run: uv run pytest --durations=10 -vv